apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 75.18.1
      helm:
        valueFiles:
        - $values/cluster-wide-k8s/kube-prometheus-stack/values.yaml
    - repoURL: 'https://github.com/navaneeth-dev/public-gitops.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/navaneeth-dev/public-gitops.git'
      targetRevision: HEAD
      path: cluster-wide-k8s/kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

