---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-machine-identity
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-machine-identity
      secretsScope:
        projectSlug: oracle-kubernetes-4x-h5
        environmentSlug: prod
        secretsPath: / # Root is "/"
        recursive: true # Default is false
      hostAPI: https://eu.infisical.com
