---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: infisical-machine-identity
  namespace: external-secrets
spec:
  encryptedData:
    clientId: AgAnXAZza+5XAF68FMwyscFiRdggEr37+UnZM5c6H7jwHaClkYxKOPrnRTHyyo6pec1JbjXob1bdO++Vn3hT3GKjh75ZifOn57awZCXM7dghWO4gb0fZMd2K/ty6iSeFg94YkUG6iSbfExWZvbEA4kfUvlU6RMD+KRGTKSRUJTHUpKEXonzN62hc+n85sjSWRo1015KAYEBvJ54AHZOBgwRz/xufk3o5N6sShZ5ZmybwNB0Kon9NZjmHgCYQYOua4Y2Jw786XyHJNfB2LqeTOd4G+aWSJqLTCA4Xp1Og+PS9Y+yyBbnYP8Tk/c/D0b6F5uXu5M9APcQTX/hJ5jQ0U7TVZtDlZZKof0GdUJheZzyksHxZlO/Wp63uxIs549zZwChOjxi/Jkbpow2taETztcoLnxXcOb6lJzikTCOLWNJINx2iPu2re/i/lira00m4eDpClPrgLzrA1oUAOsQuiobECEoTi9tx2IHXN8AFePtAU7bVFFuU5XL3j4uLAm25RYpeCCXabhh//Z6wMZ8f9UVb6oiw2JI7rrtq6/wiZ7upIQ8gsrJkF9lE/D+SF9mO3cLDpqqr0oNmw3TvcxOXfFauk8jO0rInn+N1GK675M9C3AM8tATE1a3BtspAXmhYGg+FertwhljRXSAH53BAAJaWeiIRkYPPiHkguWj7Vulg+FCUGiMFWHLBTnPZzYZHpSK2Ci9M9anuG9bRAp5wVXNnDiyv8Rp+FQO+0hd0tUTloKoMYWo=
    clientSecret: AgAqi0uBnq4NRiNvfuEc7cwOCLjiF5kmEnjHmyof2Vpup2m2wvpY2cdZjMEXO4nvI8IryKDTFQNk4a/Ct3NQ9wOqo9SCAEd8Gfip3m8wWRTgk4Ef5OOFlauoCvS+to5e2Y5QrYbSAT97G+tX9tGreMnD5UmZNhzUDpepX21WdSLM6Olyxecg6z4UlPD4h+OPj73oAPDPjQEZIMQkQg/1uk7TX0bl2ehpZ1RVhrnbKz70bKKwxnlKUh7CscV1rtv3MisF79ZYkW2jTwEKl/ePt+m5CmeneFlYEiS4moC31G3X0tXboyGwRSBkUzIyfTHHUqTdVtehvi15J4EYxQLZ1kNq/ZIIoaxbCosQGWDeUoxGSz0Xj/o4s5VsSAf+qGtuAQvX2xbL7dEyzIWJod71F8sTIGfkJ7mR84jrZqB1epmbGu2STqQONfB4lJPaEn4fEeTmfABCzYHtoYLe3a7dBJ9ZLEQ+4JYQCVNgc1cP/uIB3u+HfmwWJnJf21l4Nszbct4J9GHc7zlgEoI+LVMvGT8STyUpPcToHv9TUptWXgnSoboVQhIbmO5OEhGu0mIUwGQ+A6kWoVYOL0N9aD2lUm7f8LdVeiykhOrRRwSk6sj17PsWPO3cX6Zb671rSXhBi86W384Vp8FlYncEzFOfzQjNUVXavx0ubZppe9lVaa2v6wsH3UnR2DvF7Uo2lW96bC8ApZNEvteh2Ef1wxoxnm3CO/8yeOV0jHtuVfN/OmPpizeCaZN5472OESGpdF75rAbuuBKnFaOiNQ2i92xVt80s
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: infisical-machine-identity
      namespace: external-secrets
