---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: printquick-laravel
  namespace: staging
spec:
  encryptedData:
    APP_KEY: AgA75XztQG7A3MMhD7ymYU5LKCpfOqN0tbcTu+6Yx45APPNThbt5G/hD9t7rA0rKIZo3gIoQUeI8hPXMcVQi9Dn79J6LIWIohCWR8QhVxWzmHH2f08uVOxFSKo0r6UBOmo6PAH4rN9E0Mun3x4wAyTEXbJv/q4UWjZfUXIO7VuEwIxI7XK0pOWFqBEBWjrMhu/NEAdBNqDReKhB6vYu9cHzIR2nNTMs5c7IVwLQ7u7FKo/gzfByZXhoD2ks7BtZnZT2EgZTP0aC8pHJ+Rr5p57PEkA/bsBqly+pjRaWYv92CqtrLGVzpytD2No9EhOoGTAbjn7nGi/AoQeo+zozGytkAl0HU5h9SiFiTJEnKV8NsKzVH7kW9MHu+iuX6o2fTAvt80ftGiZsgiwAW2PMU/YH/xzGpi5iFlp+sagM4S0d20Mu+qzuOqP1nkU4MBaVI6NoSaenQNG2DVwiT6HpLTTF/LQyTYvFdOZT+SgJDUwZPn1qvT4NDQ2XUmjN3tCXX6kQVvYqV41gFFjDYW3R5nh5w6j82YFdZtzXoDnSFcJXlX2Oio7RnGgVJ2Q2+p0B4lYlCrc9F7G8M5tg+nTk66EzuQx47a/jEPT/jjD7e9kjBYEjW16IdFVVDkweeRp1zJ5iPnDhW6zc+dpsmbziMgZRgfZqfKq3y4iFmzyv6Jl/To93W3eYwSdilyzI0Au9pNgELlNTLpFiESYL7xeRZ3yxekXZYh0Tca7RPD/LpXtDWTSH+l0jNDxon2rVfLl/7HoK6/DI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: printquick-laravel
      namespace: staging
