---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/navaneeth-dev/public-gitops.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/navaneeth-dev/public-gitops.git
    targetRevision: HEAD
    path: cluster-wide-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fossindia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/navaneeth-dev/public-gitops.git
    targetRevision: HEAD
    path: fossindia
  destination:
    server: https://kubernetes.default.svc
    namespace: fossindia
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
