apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app.kubernetes.io/name: printquick
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: printquick
  template:
    metadata:
      labels:
        app.kubernetes.io/name: printquick
    spec:
      initContainers:
        - name: migrate
          image: &laravel_image ghcr.io/navaneeth-dev/printquick:0.1.0
          command: ["php", "artisan", "migrate", "--force"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: printquick-cluster-app
                  key: password
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: laravel
            - secretRef:
                name: printquick-cluster-app
        - name: migrate-tenants
          image: *laravel_image
          command: ["php", "artisan", "tenants:migrate", "--force"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: printquick-cluster-app
                  key: password
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: laravel
            - secretRef:
                name: printquick-cluster-app
      containers:
        - name: laravel
          image: *laravel_image
          ports:
            - containerPort: 8000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: printquick-cluster-app
                  key: password
          envFrom:
            - secretRef:
                name: laravel
            - configMapRef:
                name: web-config
            - secretRef:
                name: printquick-cluster-app
          livenessProbe:
            httpGet:
              path: /up
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /up
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
        - name: printquick-regcred
