---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: laravel-common
spec:
  encryptedData:
    SENTRY_LARAVEL_DSN: AgCH7Oj5XgMVhLu0+9dI1nSJgBzhTHGiJ6E5CTehwekJqyiPyb8jdnjGIGT3kT56Riv6GJ+0CA/fNb9vbLi35aw7ouYj+j7pg0hyjkie7rBz8XBuF7Bw2EvDJ8FrVCAiZ/fLmWVZ3myXovjBkV4SaM5qM4PnOtNjdc6ZbLtT1v+dMuigWdo3nngv0OAFFgnHfGhYb5pcIwEuuVRtuEHMQZdadPoW6qbqTQqMAiJF8SA5HOenv9SW8hkkBcqmPJHzqoOsDfkE1UYFOvUAKmhruvDQAkXYjkcN2BnpOT8lFCZy7Tf8iiWNbi4skav9rzAtequnFlbXXIMQtkTAipbm4oa4WzD1GCgXjYTe1XZbdNIgE2LZltP+IwE8HggEjw0J3uBiFirNJLsW/pUl1wZZo3xinUi6owmWc4Jj69nDe54E1ucqyetIOs5j5yCJqpSYREHZ9iTEY4VExylKAQMpZgHck5C5OW2y84T78rWH3fmbNqGUM6y/UQOAJlle9g4oGY/DrX+VPNgKCd/W4AeQQxD6Gb/vZ2DoDOjhJF6bNaOMv1fU6nus11fVvThSJmG67Bl/q2FbUx9JwwTk2eyRyv3yr/b7zd43O9F3+HcpgpkG7SQ+Ys7PURRoHN0aUqF/B4S81HNUNY93gRqfrQNx1BQoRkyyUGuDMtnQKCsCe/Ey3N8S3oTR979RLxV0Y8cEppRjTlrYzzc/qGO4sugaqrASpOJVMQuNCgcJfLfqXdcfrGKFwOmjtn/sah+LE8Gnl2961tEGPw+hQdnx0wLif0EouG0jHei8rsgtlMz9Znm5a7rozGvR30Ygk0LfjH8Smw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: laravel-common
