---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAB4hlimswL+SGUfuu9kF3zN4YB79SnLmX12sreNYoU3uaI+bHLjyuTgkxsmWfQPkbik3Da/v5M6fb2HONXZYHuqr8d6hVMht0nNcI2L0M6g6vpbePCTdLbzLwt5IOtENc74QPqntihdWzIDO8zttDyMJRQ7hDOBa+BEPKraVQXOt41Ph8H9wZGqcJgvoPJ4LJJwQaXb34nF9sKnBJh4BfogKcRiKsOS/ToVoCtkJyOeuExVjBwdTFJdDQgcYbMHorR3Y5O5MZaSTBhEsBgLyxXXbRxqpAbAg7ljgEWd1J6j9IdVK8/p44Sd92jeDqKpYCiYV/+rocoKt7UPDSMX/FpFpG6c6SjdL+f9orV7uuXhNf0WWpJQkXVyl/wDyU9Bu8QWjo5gkENfD8VVoytkfzhSJ4kDTplfkehujZeUl07PuzdVy04ujnkN9HyHUDPwX9YPYEj923x74MxEgdaaOm74VO//SuIxupAgyJH5ORSUmT7jWsR03Yyl9cDUgZMb6pAJCN2RoT0cHMoXDcNzA8fAF4wu8Q5Fdw27QXFgQ888HStOnEheGcaQIF3HTmFma8S8kMdNPFd6hYddLA8mMjQqo8LePJ7zUMtdnVYUGrOLP9CojbvPU9UV/+lEizuJqw+20YaNhQJpMFGcbmgLpTDgCvQxlI479l6/pIko16jKPpGMIlpgN9XFe6viYsK/xGt+dLNg7lXLOmNAD/T82lnnqRlVaFFERtzuQAED2GSdBgVxQ+3iMlC+ZMXAj6zbsa72NIXF3xUfwkr67SGfebI32nA7eRnKYP8Uo08DuzeuRs1SqGowxL8S8MEqNSSojjPYzXb/ZSwKLtapzzcTrtdd4VL5Wmgw4OUOMU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
