---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: aws-secret
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB73z2z0VeiufWy3Szp3ohh/Ymyk05NNfzjmuKchsCUIj4HAsBeSSQAV2HraAOo0vqo2KHsZOkm6QeXBw6zSvpEesjmfDF/gBmkYpnQDJaO1bN0kC6Y4XxIFW2I2PgCKhcm+d4TdLOVlZiqLJfob/X3F6yXru9Ey/2DB0PGzF13jGPhUXrHKCDr0BCTfDdt0czRcAVVj22ive0qEtZ+Z4IQBJ5Wqut8GnYOwEFyVwHG18KY6WU1VPAk+5Tyu6B63XZvj/75/d3fRei1lHd32d51G5QcfZ5Jx/MSZB7CxleIBOY5FQYnHH+l7hr7YYrOMJ5hWr5aRQ0ezMHq3kh2lX5ozpvCovX2h/uN8fvcxOoODIWjAyltYwEF0rVHTtbR9eRf+ujk8AkAT44wtegv7B7exuqKzLMugQ1FxROTcXNUTahZAhXEOZgIwcnoirtpGMLob39dUIvSoqsUkXX/Yqge9gTzBBganfpQqMMgqZ2MEmIPflSkvN6P7cusXTSaQzSBGPKaho6EHKor6CAsnP3vviiAQvl59E83lofMMbPYIYz2SExThjRJVe5LbTsj9huAJGPh30+/MA5Hahwkuyz8hOlmmXiXtu7XW/RttEcpn1aXOF+1zyPAh2AdHLHBMbs848gfN24mHjQSgf8xjb5r/BvQ3PqKAZzpmniYWGm7/AQqq+s4z1Ni6YkXYt7yuWrDjPT2fxXq+nJ4Enc57ohbskzyLQ==
    AWS_SECRET_ACCESS_KEY: AgBx3xZGDDMygPn2tKu3RnDBI9Q2MVS2evPNdWnBPeBGbzveZk3+WgyXsLLCZHFOCdsWqimV+nVjmZzHVhI0ROsGXEcWW2gvuPGwYAB2m0AdyNJGiDN6GfYf4s0cEMmGDoqY/s4aqgvhTEO4F2BbuE71VlD0N6ww0EKM5co+SSzMs06NWqCTD8Rn+40j6xsi6vMpZMN/J4akaBDwWqTcciY2sViAzRJZzVsAT9ufFe2tE/GK4vZ9Ki1LGDnED/b6tWEd11Bzb6PSEcoB14py6cSB6l0qR9rbnZRkkTdu80pJ3rR7hM/FXTFR3AAOu7AB3tjg+27jXnahJm+uuxz3kqV5WcCjso+uCCEQKSpoKiGeom8aFUCb+vWeemxUDjBHVIUdWXv3O7qtNODB2kKKLGm8HTi1nP90+uyhRO+k4hutxe/qMZTYWxxBpRp7K+TdO4pf2a/se9SFZ0kPNvm5nKnZMu5sG3yM1XpYqq8Rbp2I/mlwnFAx4cUzV8wUTGet5rVfHpqwt3dsfkz01q8ANXuWjcYfS36D3IiAPN1ujo8kOAtc/F5EMP3oMoC28K3xt4Lxhs8m3jopiadLtimaDkfzHaAb3cVRgY8xnoi0FeBP0WOzZ5mZfQCs19ch5oINuzd7gGOfK/PLFT+r9HD6ZewJ7OgU/9iqYugAreaEoWMQdMLRtDteCtvEhFT1GgrGon7MBkhmsak/pWk7n+GqfZOo9VbrgJ9/yuuOHh4QHreYqphGayF7wNis
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: aws-secret
