---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    cmds:
      - terraform apply -auto-approve
    silent: true

  destory:
    cmds:
      - terraform destroy -auto-approve
    silent: true

  recreate:
    cmds:
    - task: destory
    - task: default
    silent: true

  bootstrap:
    cmds:
      - ssh -M -S bastion -fNL 50000:10.0.60.200:50000 $(terraform output -raw bastion)
      - talosctl --talosconfig ./talosconfig dashboard
      - talosctl --talosconfig ./talosconfig bootstrap -n 10.0.10.2
      - talosctl --talosconfig ./talosconfig health -n 10.0.10.2
      - defer: ssh -S bastion -O exit $(terraform output -raw bastion)
    silent: true

  portfwd:
    cmds:
      - ssh -M -S bastion -fNL 50000:10.0.60.200:50000 $(terraform output -raw bastion)

  configs:
    cmds:
      - terraform output -raw talosconfig > ./talosconfig
      - terraform output -raw kubeconfig > ./kubeconfig
