---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    cmds:
      - terraform apply -auto-approve
    silent: true

  destory:
    cmds:
      - terraform destroy -auto-approve
    silent: true

  recreate:
    cmds:
    - task: destory
    - task: default
    silent: true

  bootstrap:
    cmds:
      - ssh -N -L 50000:10.0.0.2:22 -p 22 $(terraform output -raw bastion)
      # - talosctl --talosconfig boostrap -n 10.0.10.2
      # - talosctl --talosconfig health
    silent: true

  configs:
    cmds:
      - terraform output -raw talosconfig > ./talosconfig
      - terraform output -raw kubeconfig > ./kubeconfig
