---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-s3-creds-external-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: longhorn-backup-s3-creds

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: OVH_CLIENT_ID

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: OVH_CLIENT_SECRET

    - secretKey: VIRTUAL_HOSTED_STYLE
      remoteRef:
        key: OVH_VIRTUAL_HOSTED_STYLE

    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: OVH_AWS_ENDPOINTS
