---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: cloudflare-api-token-secret-infisical

  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN_SECRET
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-fossindia-ovh-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: certs@rize.anonaddy.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret-infisical
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-fossindia-ovh-cert
  namespace: fossindia
spec:
  secretName: prod-fossindia-ovh-tls
  dnsNames:
    - 'fossindia.ovh'
    - '*.fossindia.ovh'
  issuerRef:
    name: prod-fossindia-ovh-clusterissuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-prometheus-stack"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
