apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  routes:
    - kind: Rule
      match: Host(`attend.staging.rizexor.com`)
      services:
        - name: svc
          port: 80
  tls:
  - hosts:
    - 'staging.rizexor.com'
    secretName: staging-rizexor-com-tls
