apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  backup:
    barmanObjectStore:
      destinationPath: "s3://longhorn-oracle/attendance-v2-prod"
  storage:
    size: 1Gi
  walStorage:
    size: 5Gi
