apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1
  backup:
    barmanObjectStore:
      destinationPath: "s3://oracle-cnpg/cloudnative-pg-prod"
  storage:
    size: 1Gi
  walStorage:
    size: 5Gi
