apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  routes:
    - kind: Rule
      match: Host(`attend.prod.rizexor.com`)
      services:
        - name: svc
          port: 80
