apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-rizexor-com-cert
  namespace: default
spec:
  secretName: prod-rizexor-com-tls
  dnsNames:
    - 'prod.rizexor.com'
    - '*.prod.rizexor.com'
  issuerRef:
    name: prod-rizexor-com-issuer
    kind: ClusterIssuer

