---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: kube-prometheus-stack
spec:
  routes:
    - kind: Rule
      match: Host(`grafana.fossindia.ovh`)
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    secretName: prod-fossindia-ovh-tls
    domains:
      main: 'fossindia.ovh'
      sans:
      - '*.fossindia.ovh'

