---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack
resources:
- ./ns.yaml
- ./smtp-creds.yaml
- ./ingressroute.yaml
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/prometheusrule.yaml

