kubeControllerManager:
  enabled: false
nodeExporter:
  enabled: true
defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    configReloaders: false
    general: false
    k8s: true
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubelet: true
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    node: true
    nodeExporterAlerting: false
    nodeExporterRecording: true
    prometheus: false
    prometheusOperator: false

prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector: {}
    retention: 2d
    retentionSize: 9GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 1Gi
  ingress:
    enabled: false
    hosts:
    - grafana.fossindia.ovh
    tls:
    - secretName: prod-fossindia-ovh-tls
  smtp:
    existingSecret: "smtp-creds"
  grafana.ini:
    smtp:
      enabled: "true"
      host: "smtp.eu.mailgun.org:465"
      from_address: "grafana@mail.rizexor.com"

