---
- name: Deploy all public infrastructure services
  hosts: vps
  remote_user: ubuntu
  vars:
    CF_API_TOKEN: "{{ lookup('infisical.vault.read_secrets', project_id='e22512bb-7bb2-4e43-bcb0-e058ffccc0cd', path='/', env_slug='prod', secret_name='CLOUDFLARE_API_TOKEN_SECRET', url='https://eu.infisical.com').value }}"
  roles:
    # - role: upgrade
    - role: traefik
