---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars: {}

tasks:
  default:
    cmds:
      - mkdir -p ./target
      - mkdir -p ./target/var/lib/sops-nix
      - cp $HOME/.config/sops/age/keys.txt target/var/lib/sops-nix/key.txt
      - nix run --extra-experimental-features 'nix-command flakes' nixpkgs#nixos-anywhere -- --flake .#generic --generate-hardware-config nixos-generate-config ./hardware-configuration.nix root@155.248.245.127 --extra-files ./target
  rebuild:
    cmds:
      - mkdir -p ./target
      - mkdir -p ./target/var/lib/sops-nix
      - cp $HOME/.config/sops/age/keys.txt target/var/lib/sops-nix/key.txt
      - nix run --extra-experimental-features 'nix-command flakes' nixpkgs#nixos-rebuild -- switch --flake .#generic --target-host "root@155.248.245.127"
    silent: true
