---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  host: 141.148.204.250

tasks:
  default:
    cmds:
      - mkdir -p ./target
      - mkdir -p ./target/var/lib/sops-nix
      - cp $HOME/.config/sops/age/keys.txt target/var/lib/sops-nix/key.txt
      - nix run --extra-experimental-features 'nix-command flakes' nixpkgs#nixos-anywhere -- --flake .#generic --generate-hardware-config nixos-generate-config ./hardware-configuration.nix root@$host --extra-files ./target
    silent: true
  rebuild:
    cmds:
      - mkdir -p ./target
      - mkdir -p ./target/var/lib/sops-nix
      - cp $HOME/.config/sops/age/keys.txt target/var/lib/sops-nix/key.txt
      - nix run --extra-experimental-features 'nix-command flakes' nixpkgs#nixos-rebuild -- switch --flake .#generic --target-host "root@$host"
    silent: true
