---
- name: Download traefik and unarchive
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/traefik/traefik/releases/download/v3.4.0/traefik_v3.4.0_linux_arm64.tar.gz
    dest: /usr/bin
    include: traefik
    remote_src: true

- name: Create traefik group
  become: true
  ansible.builtin.group:
    name: "traefik"
    state: present

- name: Create traefik user
  become: true
  ansible.builtin.user:
    name: traefik
    create_home: false
    shell: /bin/false
    system: true
    group: traefik
  notify:
    - reload systemctl
    - restart traefik

- name: Copy systemd template
  become: true
  ansible.builtin.template:
    src: traefik.service
    dest: /etc/systemd/system/traefik.service
  notify:
    - reload systemctl
    - restart traefik

- name: Create /etc/letsencrypt
  become: true
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: traefik
    group: traefik

- name: Create /etc/traefik
  become: true
  ansible.builtin.file:
    path: /etc/traefik
    state: directory
    owner: traefik
    group: traefik

- name: Copy traefik.yml
  become: true
  ansible.builtin.template:
    src: traefik.yml
    dest: /etc/traefik/traefik.yml
    owner: traefik
    group: traefik
  notify: restart traefik

- name: Copy file-provider.yml
  become: true
  ansible.builtin.template:
    src: file-provider.yml
    dest: /etc/traefik/file-provider.yml
    owner: traefik
    group: traefik
  notify: restart traefik

- ansible.builtin.meta: flush_handlers
