apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1
  storage:
    storageClass: longhorn-fast
    size: 1Gi
  walStorage:
    storageClass: longhorn-fast
    size: 1Gi
  backup:
    volumeSnapshot:
       className: longhorn
    barmanObjectStore:
      destinationPath: "s3://longhorn-oracle/staging/"
      endpointURL: 'https://s3.eu-central-003.backblazeb2.com'
      wal:
        compression: gzip
      s3Credentials:
        accessKeyId:
          name: attendance-v2-aws-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: attendance-v2-aws-secret
          key: AWS_SECRET_ACCESS_KEY
    retentionPolicy: "14d"
