apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app.kubernetes.io/name: attendance-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: attendance-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: attendance-v2
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pvc
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pv-storage
          mountPath: "/var/lib/postgresql/data"
          subPath: "pg_data"
        env:
          - name: TZ
            value: "Asia/Kolkata"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: laravel
                key: DB_PASSWORD

      - name: laravel
        image: ghcr.io/onlyvels/attendance-monitoring:0.0.8
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: laravel

      - name: worker
        image: ghcr.io/onlyvels/attendance-monitoring:0.0.8
        command: ["php"]
        args: ["artisan", "queue:work"]
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: laravel

      - name: scheduler
        image: ghcr.io/onlyvels/attendance-monitoring:0.0.8
        command: ["/usr/bin/supercronic"]
        args: ["-overlapping", "/etc/supercronic/laravel"]
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: laravel

      - name: microservice
        image: ghcr.io/navaneeth-dev/attendance-microservice:0.0.5
