apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app.kubernetes.io/name: attendance-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: attendance-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: attendance-v2
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pvc
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pv-storage
          mountPath: "/var/lib/postgresql/data"
          subPath: "pg_data"
        env:
          - name: TZ
            value: "Asia/Kolkata"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-password
                key: foo

      - name: laravel
        image: ghcr.io/navaneeth-dev/attendance-v2:0.0.1
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-password
                key: foo
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: web-secrets

      - name: worker
        image: ghcr.io/navaneeth-dev/attendance-v2:0.0.1
        command: php artisan queue:work
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-password
                key: foo
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: web-secrets

      - name: microservice
        image: ghcr.io/navaneeth-dev/attendance-microservice:main
