apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app.kubernetes.io/name: attendance-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: attendance-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: attendance-v2
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pvc
      initContainers:
        - name: migrate
          image: ghcr.io/onlyvels/attendance-monitoring:0.1.2
          command: ["php", "artisan", "migrate", "--force"]
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: attendance-v2-cluster-app
                key: password
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: laravel
            - secretRef:
                name: attendance-v2-cluster-app
      containers:
      - name: laravel
        image: ghcr.io/onlyvels/attendance-monitoring:0.1.2
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: attendance-v2-cluster-app
              key: password
        envFrom:
          - secretRef:
              name: laravel
          - configMapRef:
              name: web-config
          - secretRef:
              name: attendance-v2-cluster-app

      - name: worker
        image: ghcr.io/onlyvels/attendance-monitoring:0.1.2
        command: ["php"]
        args: ["artisan", "queue:work"]
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: attendance-v2-cluster-app
              key: password
        envFrom:
          - secretRef:
              name: laravel
          - configMapRef:
              name: web-config
          - secretRef:
              name: attendance-v2-cluster-app

      - name: scheduler
        image: ghcr.io/onlyvels/attendance-monitoring:0.1.2
        command: ["/usr/bin/supercronic"]
        args: ["-overlapping", "/etc/supercronic/laravel"]
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: attendance-v2-cluster-app
              key: password
        envFrom:
          - secretRef:
              name: laravel
          - configMapRef:
              name: web-config
          - secretRef:
              name: attendance-v2-cluster-app

      - name: microservice
        image: ghcr.io/navaneeth-dev/attendance-microservice:0.0.5
