apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: attendance-v2-

resources:
- deployment.yaml
- service.yaml
- web-configmap.yaml
- cluster.yaml
- cluster-backup-schedule.yaml
- sealed-aws-secret.yaml

