---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: attendance-v2-aws-secret

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: OVH_CLIENT_ID

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: OVH_CLIENT_SECRET

