apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attendance-monitoring-pvc
spec:
  storageClassName: longhorn-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

