apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  DEBUG: "false"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_NAME: "postgres"
  CELERY_BROKER_URL: "redis://redis"

