apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.8.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 2d
            retentionSize: 9GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
        grafana:
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 1Gi
          ingress:
            enabled: true
            hosts:
              - grafana.fossindia.ovh
            tls:
              - secretName: prod-fossindia-ovh-tls
          smtp:
            existingSecret: "smtp-creds"
          grafana.ini:
            smtp:
              enabled: "true"
              host: "smtp.eu.mailgun.org:465"
              from_address: "grafana@mail.rizexor.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-creds
  namespace: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: smtp-creds

  data:
    - secretKey: user
      remoteRef:
        key: SMTP_USER
    - secretKey: password
      remoteRef:
        key: SMTP_PASSWORD
