apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: commafeed-backup
spec:
  schedule: "0 0 0 * * 1,5"
  immediate: true
  backupOwnerReference: cluster
  #method: volumeSnapshot
  method: barmanObjectStore
  cluster:
    name: fossindia-commafeed-cluster
