apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: fossindia-

resources:
- deployment.yaml
- service.yaml
- cluster.yaml
- cluster-backup-schedule.yaml
- sealed-aws-secret.yaml
- ingress.yaml
