apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  backup:
    barmanObjectStore:
      destinationPath: "s3://oracle-kubernetes/cloudnative-pg-prod"
  storage:
    size: 500Mi
  walStorage:
    size: 1Gi
