apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: printquick-

resources:
  - ../../base
  - ingress.yaml
  - sealed-laravel.yaml

patches:
  - path: web-configmap.yaml
  - path: cluster.yaml
