apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-laravel.yaml
  - sealed-laravel-s3-creds.yaml

patches:
  - path: web-configmap.yaml
  - path: cluster.yaml
  - path: ingress.yaml
