---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: laravel
  namespace: prod
spec:
  encryptedData:
    APP_KEY: AgAtdyw3pcgw737ntBXbCeDCVWr+uCqpL0Fz78VD0SztWc7cFkex6lEbhLI0ijT7sBevAD+LMmGbl+YWMG/fQD43Hot03y4JTqZ85YmLmh4kOFn49HCLzvZzfwoa3K8Nr02YyD+UezPv6GU3r47xRmwLFyw+3gllca0ygBd5DSdT2C3AUd6Gk6CzxK6DeMpN8N1f+UWzo/F+DBzEj43MZSCqjqN9h5/1J6uaSl2Tz/A1axj3zXa+wsx8M0JGdBUCfqhOC8f4pV9RmExUOxRFceJV57BM67lmL9ZOKKG5U9msFdsx8IHnzAviIdK3LEYUvgz1IsP+oD8oBY3YkwuXszif25SEDt35tTLjoji/fNEwAGHjDtDhr2CH+F0o6+M1JiEr4ebFdwSizugmePFHL7CRqrRqh1kOtedccuwTES9Qv++4B+KaEy/O8qZdl80gqF+tyYYbuP+RvtLTvOMa20MNnWZNkHd4Rkk5LjcKDAqfsk5A4vUP5m97smq8GRZJUSb8XLvKGF1cBYYkmLKEWrqJFMiRg3NcNa2Rak/g4qVvMuf6RXo+biXT/+2j4BnS9FdaeG7lDna+c8eKAh0fyVUCMvO4jg/wxBdUV1sR35CL1gA5GYksmDA8xt06TbkW5oZ5MgzemWIAgZvutI8j2kOOwyVNHSv6y6Z9M3PO48lJSLixugyuY0qCLs0K97ZEJSxP70gxIfsBwEwaYma4T8g3P6A0LFvqPLkD5UN/yj7hcTl/CkiAjKbroHKJWYgNq4MGNK4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: laravel
      namespace: prod
