apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cnpg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
