---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.13.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: infisical-machine-identity
  namespace: external-secrets
spec:
  encryptedData:
    clientId: AgC2t563LlIBh5OkeppCqaXln0CkuKAPugHfAzwRS/dEOjfHI56kp/gb9TZ/Bca2a6nI+uGeCHoqZdwQQlmWv1i8V2nAlNkg4KjaPDE17HNtmGJBiHqeM13xCwKuSKVF4P3DIJwaTcya/S7yVeW+H6cm1QAZbezABq1c0b6l32kmYfwkPHNegNCFgQ2QEulazgDXkXzOxe3D4yaYRDECD6gexfhQr1fsbrsAPr5k7X9NsUJUlgVyQ7MetqAcWh0qK7wn22z1pkKHoyyJ/0n8qLfciBnVlYQwNiki2yTyCByYxbDFLkkt9WXOKltzexmGFyvI3I5I4wwW+YHKStgToI7ctSjnCAdEevhK+6JtErnkoOp0XwDgMIJZdayzkXKxiRzkQdPi5P4ZCrzpELAoFb2uQe/7DcKebrKOtiOi7d0G+60YmGLmGvgVhhMV6YHwkmx1Epu6I378pkCa6M9oMiZt/ra4HoSiyEAGigzLjaGNFPbT4JoLDv711xf0Ln59qj7rG1s96NtF3ejTESap+LHVl2+RT4GX5Ulgo4xgdFCtRi7AIqySjMQMTx2OekzrfiM+Jij1v2U1n/JNpH7IeiePKcHpEFAfMNTfH6f/l4EuT83cT47WX4AQkVas3xHbaaXjQ2PxOlVVbSP91W7k41gnz3SZO6mBunhoPXdvHGTgVHQO/aySQ1nGPS6Zup/18HShDdnpPhxXscTCmzpv9Zo7joLdAY6VKbSub5yWmJOhRnceHUGO1w==
    clientSecret: AgAqi0uBnq4NRiNvfuEc7cwOCLjiF5kmEnjHmyof2Vpup2m2wvpY2cdZjMEXO4nvI8IryKDTFQNk4a/Ct3NQ9wOqo9SCAEd8Gfip3m8wWRTgk4Ef5OOFlauoCvS+to5e2Y5QrYbSAT97G+tX9tGreMnD5UmZNhzUDpepX21WdSLM6Olyxecg6z4UlPD4h+OPj73oAPDPjQEZIMQkQg/1uk7TX0bl2ehpZ1RVhrnbKz70bKKwxnlKUh7CscV1rtv3MisF79ZYkW2jTwEKl/ePt+m5CmeneFlYEiS4moC31G3X0tXboyGwRSBkUzIyfTHHUqTdVtehvi15J4EYxQLZ1kNq/ZIIoaxbCosQGWDeUoxGSz0Xj/o4s5VsSAf+qGtuAQvX2xbL7dEyzIWJod71F8sTIGfkJ7mR84jrZqB1epmbGu2STqQONfB4lJPaEn4fEeTmfABCzYHtoYLe3a7dBJ9ZLEQ+4JYQCVNgc1cP/uIB3u+HfmwWJnJf21l4Nszbct4J9GHc7zlgEoI+LVMvGT8STyUpPcToHv9TUptWXgnSoboVQhIbmO5OEhGu0mIUwGQ+A6kWoVYOL0N9aD2lUm7f8LdVeiykhOrRRwSk6sj17PsWPO3cX6Zb671rSXhBi86W384Vp8FlYncEzFOfzQjNUVXavx0ubZppe9lVaa2v6wsH3UnR2DvF7Uo2lW96bC8ApZNEvteh2Ef1wxoxnm3CO/8yeOV0jHtuVfN/OmPpizeCaZN5472OESGpdF75rAbuuBKnFaOiNQ2i92xVt80s
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: infisical-machine-identity
      namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-machine-identity
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-machine-identity
      secretsScope:
        projectSlug: oracle-kubernetes-4x-h5
        environmentSlug: prod
        secretsPath: / # Root is "/"
        recursive: true # Default is false
      hostAPI: https://eu.infisical.com
