apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 68.3.3
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            hosts:
            - grafana.fossindia.ovh
            tls:
            - secretName: prod-fossindia-ovh-tls
          smtp:
            existingSecret: "smtp-creds"
          grafana.ini:
            smtp:
              enabled: "true"
              host: "smtp.eu.mailgun.org"
              from_address: "grafana@mail.rizexor.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-creds
  namespace: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: smtp-creds

  data:
    - secretKey: user
      remoteRef:
        key: SMTP_USER
    - secretKey: password
      remoteRef:
        key: SMTP_PASSWORD
