---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 34.4.0
    helm:
      valuesObject:
        ports:
          http:
            redirections:
              entryPoint: websecure
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
