---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  kubernetes:
    taskfile: ./kubernetes
    dir: ./kubernetes
  oracle:
    taskfile: ./oracle
    dir: ./oracle

tasks:
  default:
    cmds:
      - task: oracle:default
      - task: kubernetes:default
    silent: true
