apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/navaneeth-dev/public-gitops.git
      revision: HEAD
      directories:
      - path: apps/*/envs/staging
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}' 
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/navaneeth-dev/public-gitops.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: 'staging'

      # Sync policy
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
