name: kubernetes
description: A minimal Kubernetes TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
